insert into livro values ('gn','Gênesis',1);
insert into livro values ('ex','Êxodo',2);
insert into livro values ('lv','Levítico',3);
insert into livro values ('nm','Números',4);
insert into livro values ('dt','Deuteronômio',5);
insert into livro values ('js','Josué',6);
insert into livro values ('jz','Juízes',7);
insert into livro values ('rt','Rute',8);
insert into livro values ('1sm','1 Samuel',9);
insert into livro values ('2sm','2 Samuel',10);
insert into livro values ('1rs','1 Reis',11);
insert into livro values ('2rs','2 Reis',12);
insert into livro values ('1cr','1 Crônicas',13);
insert into livro values ('2cr','2 Crônicas',14);
insert into livro values ('ed','Esdras',15);
insert into livro values ('ne','Neemias',16);
insert into livro values ('et','Ester',17);
insert into livro values ('j%C3%B3','Jó',18);
insert into livro values ('sl','Salmos',19);
insert into livro values ('pv','Provérbios',20);
insert into livro values ('ec','Eclesiastes',21);
insert into livro values ('ct','Cânticos',22);
insert into livro values ('is','Isaías',23);
insert into livro values ('jr','Jeremias',24);
insert into livro values ('lm','Lamentações',25);
insert into livro values ('ez','Ezequiel',26);
insert into livro values ('dn','Daniel',27);
insert into livro values ('os','Oséias',28);
insert into livro values ('jl','Joel',29);
insert into livro values ('am','Amós',30);
insert into livro values ('ob','Obadias',31);
insert into livro values ('jn','Jonas',32);
insert into livro values ('mq','Miquéias',33);
insert into livro values ('na','Naum',34);
insert into livro values ('hc','Habacuque',35);
insert into livro values ('sf','Sofonias',36);
insert into livro values ('ag','Ageu',37);
insert into livro values ('zc','Zacarias',38);
insert into livro values ('ml','Malaquias',39);
insert into livro values ('mt','Mateus',40);
insert into livro values ('mc','Marcos',41);
insert into livro values ('lc','Lucas',42);
insert into livro values ('jo','João',43);
insert into livro values ('atos','Atos',44);
insert into livro values ('rm','Romanos',45);
insert into livro values ('1co','1 Coríntios',46);
insert into livro values ('2co','2 Coríntios',47);
insert into livro values ('gl','Gálatas',48);
insert into livro values ('ef','Efésios',49);
insert into livro values ('fp','Filipenses',50);
insert into livro values ('cl','Colossenses',51);
insert into livro values ('1ts','1 Tessalonicenses',52);
insert into livro values ('2ts','2 Tessalonicenses',53);
insert into livro values ('1tm','1 Timóteo',54);
insert into livro values ('2tm','2 Timóteo',55);
insert into livro values ('tt','Tito',56);
insert into livro values ('fm','Filemom',57);
insert into livro values ('hb','Hebreus',58);
insert into livro values ('tg','Tiago',59);
insert into livro values ('1pe','1 Pedro',60);
insert into livro values ('2pe','2 Pedro',61);
insert into livro values ('1jo','1 João',62);
insert into livro values ('2jo','2 João',63);
insert into livro values ('3jo','3 João',64);
insert into livro values ('jd','Judas',65);
insert into livro values ('ap','Apocalipse',66);
